name: Build and Push Chat Service

on:
  push:
    branches:
      - main
    paths:
      - 'services/chat/**'
      - 'libraries/**'
  workflow_dispatch:

jobs:
  build-chat:
    uses: ./.github/workflows/build-push-template.yml
    with:
      service: chat
      image_tag: ai-tutor
    secrets: inherit
